on:
  push:
    branches:
      - 'main'
    paths:
      - '*.yml'
      - 'modules/*.yml'
  pull_request:
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab
name: Build Flatpak
jobs:
  flatpak:
    name: Flatpak Builder
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15-23.08
      options: --privileged
      
    steps:
    - name: Clean
      shell: bash
      run: |
        echo "Available storage before cleaning:"
        df -h
        
        # inspired by https://github.com/easimon/maximize-build-space
        for label_with_path in \
              "Android SDK:/usr/local/lib/android" \
              "CodeQL:/opt/hostedtoolcache/CodeQL" \
              "Haskell:/opt/ghc" \
              ".NET:/usr/share/dotnet"; do
          dependency_name="$(echo "${label_with_path}" | cut -d: -f1)"
          dependency_path="$(echo "${label_with_path}" | cut -d: -f2)"
        
          if [ -d "${dependency_path}" ]; then
            echo "[INFO] Deleting binaries of ${dependency_name} in ${dependency_path}."
            sudo rm -rf "${dependency_path}"
            df -h
          else
            echo "[INFO] The directory '${dependency_path}' doesn't exist. ${dependency_name} won't be removed."
          fi
        done

        echo "Available storage before cleaning:"
        df -h
          
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Cache
      id: cache
      uses: actions/cache@v4
      with:
        path: .flatpak-builder
        key: flatpak-build-${{ github.sha }}
        restore-keys: flatpak-build
        save-always: true
        
    - name: Build
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: kadas.flatpak
        manifest-path: com.sourcepole.kadas.yml
        cache: false
